"""CDBR Global Variables"""
cdbr_normal_resolve = None
cdbr_state = None
cdbr_query_strings = None
cdbr_query_results = None
cdbr_node_to_index = None
cdbr_player = None
max_id = 0
cdbr_opponent_range = None
