"""CDBR Global Variables"""
cdbr_normal_resolve = None
cdbr_state = None
cdbr_query_strings = None
cdbr_query_results = None
cdbr_node_to_index = None
cdbr_player = None
max_id = 0
cdbr_opponent_range = None
cdbr_exploited = False
cdbr_exploiter = False
cdbr_exploited_results = None
cdbr_exploitation_id = None
cdbr_exploited_ready = False
cdbr_exploiter_prev_node = None
